In [5]:
import pandas as pd
data=pd.read_csv("D:/sql/sales.csv")

In [6]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [7]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [9]:
data.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [8]:
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [11]:
data["Postal Code"]

0       42420.0
1       42420.0
2       90036.0
3       33311.0
4       33311.0
         ...
9795    60610.0
9796    43615.0
9797    43615.0
9798    43615.0
9799    43615.0
Name: Postal Code, Length: 9800, dtype: float64

In [16]:
data.duplicated().sum()

np.int64(0)

In [9]:
data["Postal Code"].ffill()

0       42420.0
1       42420.0
2       90036.0
3       33311.0
4       33311.0
         ...
9795    60610.0
9796    43615.0
9797    43615.0
9798    43615.0
9799    43615.0
Name: Postal Code, Length: 9800, dtype: float64

In [10]:
data.shape

(9800, 18)

In [11]:
data=data.dropna()

In [12]:
data.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [13]:
#creating business KPIs used in real worlds caese

total_sales = data["Sales"].sum()
total_sales

np.float64(2252607.4127)

In [14]:
total_orders = data["Order ID"].nunique()
total_orders

4916

In [15]:
total_customers = data["Customer ID"].nunique()
total_customers

793

In [16]:
avg_orders =( data["Sales"].sum() / data["Order ID"].nunique() )
avg_orders

np.float64(458.2195713384866)

In [17]:
#Business analysis

region_sales = data.groupby("Region")["Sales"].sum().sort_values(ascending=False)
region_sales

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [18]:
#which region has highest sales
region_sales.max()

np.float64(710219.6845)

In [19]:
#which category sales most happened

category_sales = data.groupby("Category")["Sales"].sum()
category_sales
category_sales.max()

np.float64(825856.113)

In [20]:
#Top most customers 10 

top_customers = data.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)
top_customers

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [21]:
#top procuts saled

top_products = data.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)
top_products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [62]:
#lowest sales products

top_products = data.groupby("Product Name")["Sales"].sum().sort_values(ascending=True).head(10)
top_products

Product Name
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac    1.624
Avery 5                                                             5.760
Xerox 20                                                            6.480
Grip Seal Envelopes                                                 7.072
Acme Serrated Blade Letter Opener                                   7.632
Avery Hi-Liter Pen Style Six-Color Fluorescent Set                  7.700
Avery Hi-Liter Comfort Grip Fluorescent Highlighter, Yellow Ink     7.800
Xerox 1989                                                          7.968
Stockwell Gold Paper Clips                                          8.096
Acco Economy Flexible Poly Round Ring Binder                        8.352
Name: Sales, dtype: float64

In [22]:
#least customers made sales

top_customers = data.groupby("Customer Name")["Sales"].sum().sort_values(ascending=True).head(10)
top_customers

Customer Name
Thais Sissman       4.833
Lela Donovan        5.304
Sung Chung         14.112
Carl Jackson       16.520
Mitch Gastineau    16.739
Roy Skaria         22.328
Susan Gilcrest     47.946
Ricardo Emerson    48.360
Ionia McGrath      48.400
Larry Blacks       50.188
Name: Sales, dtype: float64

In [23]:
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
data["Order Date"] = pd.to_datetime(
    data["Order Date"],
    dayfirst=True
)

In [25]:

monthly_sales = (
    data.groupby(
        pd.Grouper(
            key="Order Date",
            freq="ME"
        )
    )["Sales"]
    .sum()
)

In [26]:
monthly_sales.head(5)

Order Date
2015-01-31    14205.707
2015-02-28     4519.892
2015-03-31    55205.797
2015-04-30    27906.855
2015-05-31    23644.303
Freq: ME, Name: Sales, dtype: float64

In [2]:
from prophet import Prophet

Importing plotly failed. Interactive plots will not work.

In [27]:
#preparing data for forecasting

forecast_data = monthly_sales.reset_index()

forecast_data.columns = ["ds", "y"]

forecast_data.head()

          ds          y
0 2015-01-31  14205.707
1 2015-02-28   4519.892
2 2015-03-31  55205.797
3 2015-04-30  27906.855
4 2015-05-31  23644.303

In [28]:

model = Prophet()

model.fit(forecast_data)

18:56:30 - cmdstanpy - INFO - Chain [1] start processing
18:56:35 - cmdstanpy - INFO - Chain [1] done processing

In [29]:
future = model.make_future_dataframe(
    periods=6,
    freq="ME"
)

In [35]:
#predict future sales
#actual prediction
forecast = model.predict(future)

In [36]:
forecast[["ds","yhat"]].tail(10)
#viewing of th e prediions

           ds           yhat
44 2018-09-30   89233.940583
45 2018-10-31   61771.239158
46 2018-11-30  100780.233479
47 2018-12-31   90797.816853
48 2019-01-31   42942.922174
49 2019-02-28   31284.729218
50 2019-03-31   81616.839937
51 2019-04-30   51128.751738
52 2019-05-31   53308.272076
53 2019-06-30   60821.695680

In [38]:
#saving forecast time series results

forecast_results = forecast[["ds","yhat"]]

forecast_results.to_csv(
    "sales_forecast.csv",
    index=False
)

In [39]:
monthly_sales.head(5)

Order Date
2015-01-31    14205.707
2015-02-28     4519.892
2015-03-31    55205.797
2015-04-30    27906.855
2015-05-31    23644.303
Freq: ME, Name: Sales, dtype: float64

In [40]:
monthly_sales_data = monthly_sales.reset_index()

monthly_sales_data.to_csv(
    "monthly_sales.csv",
    index=False
)